/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"
#include <string.h>
#include <stdio.h>
int set[101];
int lock = 1;

char **
test_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
	static char tmp_char[128];
	
	int port = rqstp->rq_xprt->xp_raddr.sin_port, addr = rqstp->rq_xprt->xp_raddr.sin_addr.s_addr, key = (port % 10 + 1) * (addr % 10 + 1) ;

	if (strcmp(argp,"acquire") == 0)
	{
		if (set[key] == 0 && lock > 0) 
		{
			set[key] = 1;
			sprintf(tmp_char,"Sucess, server give a lock to client(%d : %d).\n",addr,port);
		}else if(lock <= 0){
			sprintf(tmp_char,"Failed , lack of lock.\n");
		}
		else{
			sprintf(tmp_char,"Failed, server has already given a lock to client(%d : %d).\n",addr,port);	
		}
	}else if (strcmp(argp,"release") == 0)
	{
		if (set[key] == 1)
		{
			set[key] = 0;
			sprintf(tmp_char,"Success, server release a lock from client(%d : %d).\n", addr, port);
		}else{
			sprintf(tmp_char,"Failed, server has not given a lock to client(%d : %d).\n", addr, port);
		}
	}else{
		sprintf(tmp_char , "Operation ERROR!\n");
	}
	result = tmp_char;

	return &result;
}
