/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"
#include <string.h>

void
testprog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * test_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	char *input;
	printf("Please enter your lock operation--acquire , release or exit.\n");
	while(1){
		scanf("%s",input);
		if(strcmp(input,"exit") == 0){
			input = "release";
			test_1(&input,clnt);
			printf("Login out.\n");
			break;
		}
		result_1 = test_1(&input,clnt);
		if(result_1 == (char **) NULL){
			clnt_perror(clnt, "call failed");
		}
		printf("%s",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	testprog_1 (host);
exit (0);
}
